apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  ports:
    - port: 8025
      name: app
      targetPort: app
  type: LoadBalancer
  selector:
    app: mailhog
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mailhog
spec:
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          ports:
            - containerPort: 8025
              name: app

